import * as THREE from 'https://unpkg.com/three@0.161.0/build/three.module.js';

class PlayerController{
  constructor(game){this.game=game;this.pos=new THREE.Vector3(0,1.7,8);this.vel=new THREE.Vector3();this.yaw=0;this.pitch=0;this.speed=7;this.sprint=11;this.grounded=false;this.keys={};this.health=new PlayerHealth(game);window.addEventListener('keydown',e=>{this.keys[e.code]=true;if(e.code==='KeyR')game.weapon.reload();if(e.code==='Escape')game.togglePause();});window.addEventListener('keyup',e=>this.keys[e.code]=false);window.addEventListener('mousemove',e=>{if(!game.playing||game.paused)return;this.yaw-=e.movementX*.0022;this.pitch=Math.max(-1.35,Math.min(1.25,this.pitch-e.movementY*.0022));});}
  update(dt){const g=this.game;if(!g.playing||g.paused)return;let dir=new THREE.Vector3((this.keys.KeyD?1:0)-(this.keys.KeyA?1:0),0,(this.keys.KeyS?1:0)-(this.keys.KeyW?1:0));if(dir.lengthSq())dir.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),this.yaw);let sp=this.keys.ShiftLeft||this.keys.ShiftRight?this.sprint:this.speed;this.vel.x=dir.x*sp;this.vel.z=dir.z*sp;this.vel.y-=22*dt;if(this.grounded&&this.keys.Space){this.vel.y=8.5;this.grounded=false}this.pos.addScaledVector(this.vel,dt);if(this.pos.y<1.7){this.pos.y=1.7;this.vel.y=0;this.grounded=true}const lim=27;this.pos.x=Math.max(-lim,Math.min(lim,this.pos.x));this.pos.z=Math.max(-lim,Math.min(lim,this.pos.z));g.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');g.camera.position.copy(this.pos);g.weapon.update(dt);}
}
class PlayerHealth{constructor(game){this.game=game;this.hp=100}damage(v){if(!this.game.playing)return;this.hp=Math.max(0,this.hp-v);this.game.flashDamage();if(this.hp<=0)this.game.end(false)}}
class Weapon{constructor(game){this.game=game;this.mag=30;this.ammo=30;this.rate=.09;this.cool=0;this.reloading=0;this.group=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.18,.18,.8),new THREE.MeshStandardMaterial({color:0x22272e,metalness:.5,roughness:.4}));body.position.set(.34,-.28,-.55);this.muzzle=new THREE.PointLight(0xffcc77,0,2);this.muzzle.position.set(.34,-.25,-1);this.group.add(body,this.muzzle);game.camera.add(this.group);window.addEventListener('mousedown',e=>{if(e.button===0)this.firing=true});window.addEventListener('mouseup',e=>{if(e.button===0)this.firing=false});}
 update(dt){this.cool-=dt;if(this.reloading>0){this.reloading-=dt;if(this.reloading<=0)this.ammo=this.mag;return}if(this.firing&&this.cool<=0)this.fire();this.muzzle.intensity=Math.max(0,this.muzzle.intensity-90*dt)}
 reload(){if(this.ammo<this.mag&&this.reloading<=0)this.reloading=1.25}
 fire(){if(this.ammo<=0){this.reload();return}this.ammo--;this.cool=this.rate;this.muzzle.intensity=7;this.game.camera.rotation.x+=.018;const ray=new THREE.Raycaster(this.game.camera.position,this.game.camera.getWorldDirection(new THREE.Vector3()),0,75);const hits=ray.intersectObjects(this.game.enemyMeshes,false);if(hits[0]){const enemy=hits[0].object.userData.enemy;enemy.hit(34);this.game.spawnHit(hits[0].point)}}}
class Enemy{constructor(game,type,pos){this.game=game;const cfg={grunt:[70,3.1,8,100],fast:[45,5.0,6,140],heavy:[150,2.2,16,250]}[type];[this.hp,this.speed,this.damage,this.points]=cfg;this.cool=0;this.mesh=new THREE.Mesh(new THREE.CapsuleGeometry(type==='heavy'?0.75:.5,type==='heavy'?1.5:1,5,10),new THREE.MeshStandardMaterial({color:type==='fast'?0xff8844:type==='heavy'?0x8b3bff:0x43e06d,roughness:.75}));this.mesh.position.copy(pos);this.mesh.userData.enemy=this;game.scene.add(this.mesh);game.enemies.push(this);game.enemyMeshes.push(this.mesh)}
 update(dt){const p=this.game.player.pos;const to=p.clone().sub(this.mesh.position);to.y=0;const d=to.length();if(d>1.4){to.normalize();this.mesh.position.addScaledVector(to,this.speed*dt);this.mesh.lookAt(p.x,this.mesh.position.y,p.z)}else{this.cool-=dt;if(this.cool<=0){this.cool=.8;this.game.player.health.damage(this.damage)}}}
 hit(v){this.hp-=v;if(this.hp<=0)this.die()}die(){this.game.score.add(this.points);this.game.scene.remove(this.mesh);this.game.enemies=this.game.enemies.filter(e=>e!==this);this.game.enemyMeshes=this.game.enemyMeshes.filter(m=>m!==this.mesh)}}
class WaveManager{constructor(game){this.game=game;this.wave=0;this.left=0;this.pause=2;this.counts=[5,8,12,16,20];this.spawns=[[-22,0,-22],[22,0,-22],[-22,0,22],[22,0,22],[0,0,-24],[0,0,24]].map(a=>new THREE.Vector3(a[0],1,a[2]));}
 update(dt){if(!this.game.playing||this.game.paused)return;if(this.left<=0&&this.game.enemies.length===0){if(this.wave>=5){this.game.end(true);return}this.pause-=dt;if(this.pause<=0)this.start()} }
 start(){this.wave++;this.left=this.counts[this.wave-1];this.game.message('WAVE '+this.wave,1400);for(let i=0;i<this.left;i++)setTimeout(()=>this.spawn(),i*550);this.pause=3}
 spawn(){if(!this.game.playing)return;const type=this.wave>3&&Math.random()<.25?'heavy':(this.wave>1&&Math.random()<.35?'fast':'grunt');new Enemy(this.game,type,this.spawns[Math.floor(Math.random()*this.spawns.length)].clone());this.left--}}
class ScoreManager{constructor(){this.value=0}add(v){this.value+=v}}
class UIManager{constructor(game){this.game=game;this.el=document.getElementById('ui')}render(){const g=this.game;if(!g.playing)return;this.el.innerHTML=`<div class="hud">HP: ${Math.ceil(g.player.health.hp)}<div class="bar"><div class="fill" style="width:${g.player.health.hp}%"></div></div>WAVE: ${g.waves.wave||1}<br>SCORE: ${g.score.value}</div><div class="hud right">AMMO: ${g.weapon.ammo} / ∞<br>ENEMIES: ${g.enemies.length+g.waves.left}<br>${g.weapon.reloading>0?'RELOADING':''}</div><div class="center">${g.note||''}</div>`}}
class GameManager{constructor(){this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x111820);this.scene.fog=new THREE.Fog(0x111820,20,80);this.camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.1,200);this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;document.body.appendChild(this.renderer.domElement);this.scene.add(this.camera);this.clock=new THREE.Clock();this.enemies=[];this.enemyMeshes=[];this.score=new ScoreManager();this.ui=new UIManager(this);this.makeWorld();this.menu();addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)});requestAnimationFrame(()=>this.loop())}
 makeWorld(){this.scene.add(new THREE.HemisphereLight(0x9bbcff,0x202018,1.7));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(10,20,5);sun.castShadow=true;this.scene.add(sun);const mat=new THREE.MeshStandardMaterial({color:0x33414a,roughness:.9});const floor=new THREE.Mesh(new THREE.BoxGeometry(60,1,60),mat);floor.position.y=-.55;floor.receiveShadow=true;this.scene.add(floor);const wallMat=new THREE.MeshStandardMaterial({color:0x56616e});for(const [x,z,sx,sz] of [[0,-30,60,2],[0,30,60,2],[-30,0,2,60],[30,0,2,60]]){let w=new THREE.Mesh(new THREE.BoxGeometry(sx,5,sz),wallMat);w.position.set(x,2,z);w.castShadow=w.receiveShadow=true;this.scene.add(w)}const colors=[0x2f516b,0x6b5130,0x404040];for(let i=0;i<28;i++){let b=new THREE.Mesh(new THREE.BoxGeometry(2+Math.random()*3,1+Math.random()*3,2+Math.random()*3),new THREE.MeshStandardMaterial({color:colors[i%3]}));b.position.set((Math.random()-.5)*45,b.geometry.parameters.height/2-.05,(Math.random()-.5)*45);b.castShadow=b.receiveShadow=true;this.scene.add(b)}for(let i=0;i<8;i++){let c=new THREE.Mesh(new THREE.CylinderGeometry(.65,.65,4,12),new THREE.MeshStandardMaterial({color:0x8a8a8a}));c.position.set(Math.cos(i)*16,2,Math.sin(i)*16);c.castShadow=c.receiveShadow=true;this.scene.add(c)}}
 menu(){this.playing=false;this.ui.el.innerHTML=`<div class="menu"><h1>ARENA SHOOTER</h1><button id="play">PLAY</button><button onclick="window.close()">QUIT</button><p class="hint">WASD move, Mouse look, LMB fire, R reload, Shift sprint, Space jump, Esc pause. Survive five waves.</p></div>`;document.getElementById('play').onclick=()=>this.start()}
 start(){this.playing=true;this.paused=false;this.enemies.forEach(e=>this.scene.remove(e.mesh));this.enemies=[];this.enemyMeshes=[];this.player=new PlayerController(this);this.weapon=new Weapon(this);this.waves=new WaveManager(this);this.score.value=0;document.body.requestPointerLock?.();}
 togglePause(){if(!this.playing)return;this.paused=!this.paused;this.message(this.paused?'PAUSED':'',999999)}message(t,ms){this.note=t;clearTimeout(this.msgTimer);if(ms<999999)this.msgTimer=setTimeout(()=>this.note='',ms)}flashDamage(){const d=document.createElement('div');d.className='damage';this.ui.el.appendChild(d);setTimeout(()=>d.remove(),260)}spawnHit(p){const s=new THREE.Mesh(new THREE.SphereGeometry(.13,8,8),new THREE.MeshBasicMaterial({color:0xffdd66}));s.position.copy(p);this.scene.add(s);setTimeout(()=>this.scene.remove(s),120)}end(win){this.playing=false;document.exitPointerLock?.();this.ui.el.innerHTML=`<div class="menu"><h1>${win?'YOU WIN!':'YOU DIED'}</h1><p>SCORE: ${this.score.value}</p><button id="play">RESTART</button></div>`;document.getElementById('play').onclick=()=>this.start()}
 loop(){const dt=Math.min(.033,this.clock.getDelta());if(this.playing&&!this.paused){this.player.update(dt);this.enemies.slice().forEach(e=>e.update(dt));this.waves.update(dt)}this.ui.render();this.renderer.render(this.scene,this.camera);requestAnimationFrame(()=>this.loop())}}
new GameManager();
